import type { Client, Task, User } from '../types';

// Mock user data
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@caoffice.com',
    name: 'Admin User',
    role: 'admin',
  },
  {
    id: '2',
    email: 'staff@caoffice.com',
    name: 'Staff Member',
    role: 'staff',
  },
];

// Mock client data
export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Acme Corporation',
    pan: 'ABCDE1234F',
    gstin: '27ABCDE1234F1Z5',
    email: 'finance@acme.com',
    phone: '+91 9876543210',
    status: 'active',
    nextDueDate: '2025-01-15',
    address: '123 Business Park, Mumbai, Maharashtra',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Tech Solutions Pvt Ltd',
    pan: 'FGHIJ5678K',
    gstin: '29FGHIJ5678K1Z3',
    email: 'accounts@techsolutions.in',
    phone: '+91 9876543211',
    status: 'active',
    nextDueDate: '2025-01-20',
    address: '456 Tech Hub, Bangalore, Karnataka',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Global Traders',
    pan: 'KLMNO9012P',
    email: 'info@globaltraders.com',
    phone: '+91 9876543212',
    status: 'inactive',
    address: '789 Trade Center, Delhi',
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'Sunrise Industries',
    pan: 'PQRST3456U',
    gstin: '07PQRST3456U1Z9',
    email: 'finance@sunrise.co.in',
    phone: '+91 9876543213',
    status: 'active',
    nextDueDate: '2025-02-01',
    address: '321 Industrial Area, Noida, UP',
    createdAt: '2024-04-05',
  },
  {
    id: '5',
    name: 'Creative Solutions',
    pan: 'UVWXY7890Z',
    email: 'accounts@creative.in',
    phone: '+91 9876543214',
    status: 'active',
    nextDueDate: '2025-01-25',
    address: '555 Design Street, Pune, Maharashtra',
    createdAt: '2024-05-12',
  },
];

// Mock task data
export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'GST Return - Q3 Filing',
    description: 'File quarterly GST return for Q3 FY 2024-25',
    clientId: '1',
    clientName: 'Acme Corporation',
    type: 'GST',
    status: 'pending',
    priority: 'high',
    dueDate: '2025-01-15',
    assignee: 'Staff Member',
    createdAt: '2024-12-01',
  },
  {
    id: '2',
    title: 'Income Tax Return Filing',
    description: 'Prepare and file ITR for AY 2024-25',
    clientId: '2',
    clientName: 'Tech Solutions Pvt Ltd',
    type: 'ITR',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2025-01-20',
    assignee: 'Admin User',
    createdAt: '2024-12-05',
  },
  {
    id: '3',
    title: 'TDS Quarterly Return',
    description: 'File TDS return for Q3',
    clientId: '1',
    clientName: 'Acme Corporation',
    type: 'TDS',
    status: 'completed',
    priority: 'medium',
    dueDate: '2024-12-31',
    assignee: 'Staff Member',
    createdAt: '2024-11-15',
  },
  {
    id: '4',
    title: 'Annual Audit',
    description: 'Complete statutory audit for FY 2023-24',
    clientId: '4',
    clientName: 'Sunrise Industries',
    type: 'Audit',
    status: 'overdue',
    priority: 'high',
    dueDate: '2024-12-15',
    assignee: 'Admin User',
    createdAt: '2024-10-01',
  },
  {
    id: '5',
    title: 'ROC Annual Filing',
    description: 'File annual returns with ROC',
    clientId: '5',
    clientName: 'Creative Solutions',
    type: 'ROC',
    status: 'pending',
    priority: 'low',
    dueDate: '2025-01-30',
    assignee: 'Staff Member',
    createdAt: '2024-12-10',
  },
  {
    id: '6',
    title: 'GST Registration',
    description: 'New GST registration application',
    clientId: '3',
    clientName: 'Global Traders',
    type: 'GST',
    status: 'in-progress',
    priority: 'medium',
    dueDate: '2025-01-10',
    assignee: 'Admin User',
    createdAt: '2024-12-20',
  },
];
